services:
  - type: web
    name: saas-payment-hub
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # /!\ RENSEIGNEZ VOTRE URL NEON.TECH ICI LORS DU DEPLOIEMENT /!\
      - key: DATABASE_URL
        value: postgres://user:password@ep-nom-de-base.region.aws.neon.tech/neondb
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: HUB_BASE_URL
        value: https://saas-payment-hub.onrender.com # Change this once deployed or using custom domain
      - key: CLIENT_APPS
        value: '[{"id":"boutique1","name":"Ma Boutique Demo","apiKey":"secret_api_key_123","webhookUrl":""}]'
